/// Differential Evolution (DE/rand/1/bin) optimizer.
///
/// Well-suited for the mixed continuous/discrete parameter space of noise
/// presets. Population-based, gradient-free, handles non-convex landscapes.
use rand::prelude::*;
use rand_distr::Uniform;

/// Result of one evaluation.
#[derive(Clone)]
pub struct Individual {
    pub genome: Vec<f64>,
    pub fitness: f64,
}

pub struct DifferentialEvolution {
    /// Population of candidate solutions.
    population: Vec<Individual>,
    /// Best individual found so far.
    best: Individual,
    /// Parameter bounds: (min, max) per dimension.
    bounds: Vec<(f64, f64)>,
    /// Mutation scale factor.
    f: f64,
    /// Crossover probability.
    cr: f64,
    /// Current generation.
    generation: usize,
    /// RNG
    rng: StdRng,
    /// Indices of discrete (integer-valued) dimensions to round after mutation.
    discrete_dims: Vec<usize>,
}

impl DifferentialEvolution {
    /// Create a new DE optimizer.
    ///
    /// - `bounds`: (min, max) for each dimension
    /// - `pop_size`: population size (typically 5–10× the dimension count)
    /// - `f`: mutation scale (0.5–0.9 typical)
    /// - `cr`: crossover rate (0.7–0.9 typical)
    /// - `seed`: RNG seed for reproducibility
    pub fn new(bounds: Vec<(f64, f64)>, pop_size: usize, f: f64, cr: f64, seed: u64) -> Self {
        Self::with_discrete(bounds, pop_size, f, cr, seed, Vec::new())
    }

    /// Create a new DE optimizer with discrete dimension indices.
    ///
    /// Genes at `discrete_dims` indices are rounded to the nearest integer
    /// after mutation and crossover, preventing the algorithm from wasting
    /// evaluations on continuous values that map to the same discrete setting.
    pub fn with_discrete(
        bounds: Vec<(f64, f64)>,
        pop_size: usize,
        f: f64,
        cr: f64,
        seed: u64,
        discrete_dims: Vec<usize>,
    ) -> Self {
        let dim = bounds.len();
        let mut rng = StdRng::seed_from_u64(seed);

        // Initialise population with uniform random samples
        let population: Vec<Individual> = (0..pop_size)
            .map(|_| {
                let genome: Vec<f64> = bounds
                    .iter()
                    .map(|(lo, hi)| rng.sample(Uniform::new(*lo, *hi)))
                    .collect();
                Individual {
                    genome,
                    fitness: f64::NEG_INFINITY,
                }
            })
            .collect();

        let best = Individual {
            genome: vec![0.0; dim],
            fitness: f64::NEG_INFINITY,
        };

        let mut de = DifferentialEvolution {
            population,
            best,
            bounds,
            f,
            cr,
            generation: 0,
            rng,
            discrete_dims,
        };

        // Round discrete genes in the initial population
        de.round_discrete_all();
        de
    }

    /// Replace the population with perturbations of a seed genome.
    ///
    /// The seed itself is placed at index 0. The rest of the population is
    /// generated by perturbing each gene by ±perturbation_frac of its range,
    /// clamped to bounds.
    pub fn seed_from_genome(&mut self, seed: &[f64], perturbation_frac: f64) {
        for (i, ind) in self.population.iter_mut().enumerate() {
            if i == 0 {
                ind.genome = seed.to_vec();
            } else {
                ind.genome = seed
                    .iter()
                    .zip(self.bounds.iter())
                    .map(|(g, (lo, hi))| {
                        let range = hi - lo;
                        let delta = self
                            .rng
                            .sample(Uniform::new(-perturbation_frac, perturbation_frac))
                            * range;
                        (g + delta).clamp(*lo, *hi)
                    })
                    .collect();
            }
            ind.fitness = f64::NEG_INFINITY;
        }
        self.round_discrete_all();
    }

    /// Get all individuals that need evaluation (fitness == NEG_INFINITY).
    pub fn pending_evaluations(&self) -> Vec<(usize, Vec<f64>)> {
        self.population
            .iter()
            .enumerate()
            .filter(|(_, ind)| ind.fitness == f64::NEG_INFINITY)
            .map(|(i, ind)| (i, ind.genome.clone()))
            .collect()
    }

    /// Report fitness for an individual.
    pub fn report_fitness(&mut self, index: usize, fitness: f64) {
        self.population[index].fitness = fitness;
        if fitness > self.best.fitness {
            self.best = self.population[index].clone();
        }
    }

    /// Run one generation of DE. Returns trial vectors to evaluate.
    ///
    /// Call `report_trial_results()` after evaluating each trial.
    pub fn generate_trials(&mut self) -> Vec<(usize, Vec<f64>)> {
        let pop_size = self.population.len();
        let dim = self.bounds.len();
        let mut trials = Vec::with_capacity(pop_size);

        for i in 0..pop_size {
            // Select three distinct random individuals (not i)
            let (a, b, c) = self.pick_three(i);

            // Mutation: donor = a + F * (b - c)
            let mut trial = vec![0.0; dim];
            let j_rand = self.rng.gen_range(0..dim);

            for j in 0..dim {
                // Binomial crossover
                if self.rng.gen::<f64>() < self.cr || j == j_rand {
                    let mutant = self.population[a].genome[j]
                        + self.f * (self.population[b].genome[j] - self.population[c].genome[j]);
                    trial[j] = self.clamp_to_bounds(j, mutant);
                } else {
                    trial[j] = self.population[i].genome[j];
                }
            }

            self.round_discrete(&mut trial);
            trials.push((i, trial));
        }

        self.generation += 1;
        trials
    }

    /// Report trial evaluation results. Replaces parent if trial is better.
    pub fn report_trial_result(
        &mut self,
        target_index: usize,
        trial_genome: Vec<f64>,
        trial_fitness: f64,
    ) {
        if trial_fitness >= self.population[target_index].fitness {
            self.population[target_index] = Individual {
                genome: trial_genome,
                fitness: trial_fitness,
            };
            if trial_fitness > self.best.fitness {
                self.best = self.population[target_index].clone();
            }
        }
    }

    /// Best individual found so far.
    pub fn best(&self) -> &Individual {
        &self.best
    }

    pub fn generation(&self) -> usize {
        self.generation
    }

    /// Mean fitness of current population.
    pub fn mean_fitness(&self) -> f64 {
        let valid: Vec<f64> = self
            .population
            .iter()
            .filter(|i| i.fitness > f64::NEG_INFINITY)
            .map(|i| i.fitness)
            .collect();
        if valid.is_empty() {
            return 0.0;
        }
        valid.iter().sum::<f64>() / valid.len() as f64
    }

    /// Fitness standard deviation of current population.
    pub fn fitness_std(&self) -> f64 {
        let valid: Vec<f64> = self
            .population
            .iter()
            .filter(|i| i.fitness > f64::NEG_INFINITY)
            .map(|i| i.fitness)
            .collect();
        if valid.len() < 2 {
            return 0.0;
        }
        let mean = valid.iter().sum::<f64>() / valid.len() as f64;
        let var = valid.iter().map(|x| (x - mean).powi(2)).sum::<f64>() / valid.len() as f64;
        var.sqrt()
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    /// Round discrete genes in a single genome vector.
    fn round_discrete(&self, genome: &mut [f64]) {
        for &d in &self.discrete_dims {
            genome[d] = genome[d].round();
        }
    }

    /// Round discrete genes in the entire population.
    fn round_discrete_all(&mut self) {
        let dims: Vec<usize> = self.discrete_dims.clone();
        for ind in &mut self.population {
            for &d in &dims {
                ind.genome[d] = ind.genome[d].round();
            }
        }
    }

    fn pick_three(&mut self, exclude: usize) -> (usize, usize, usize) {
        let pop_size = self.population.len();
        let mut a = exclude;
        while a == exclude {
            a = self.rng.gen_range(0..pop_size);
        }
        let mut b = exclude;
        while b == exclude || b == a {
            b = self.rng.gen_range(0..pop_size);
        }
        let mut c = exclude;
        while c == exclude || c == a || c == b {
            c = self.rng.gen_range(0..pop_size);
        }
        (a, b, c)
    }

    /// Clamp value to the bounds for the given dimension.
    fn clamp_to_bounds(&self, dim: usize, value: f64) -> f64 {
        let (lo, hi) = self.bounds[dim];
        value.clamp(lo, hi)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn simple_bounds(dim: usize) -> Vec<(f64, f64)> {
        vec![(-5.0, 5.0); dim]
    }

    // ---------------------------------------------------------------
    // Construction
    // ---------------------------------------------------------------

    #[test]
    fn population_has_correct_size() {
        let de = DifferentialEvolution::new(simple_bounds(3), 20, 0.8, 0.9, 42);
        assert_eq!(de.population.len(), 20);
    }

    #[test]
    fn initial_population_within_bounds() {
        let bounds = vec![(-2.0, 3.0), (0.0, 10.0), (-1.0, 1.0)];
        let de = DifferentialEvolution::new(bounds.clone(), 50, 0.8, 0.9, 42);
        for ind in &de.population {
            for (j, &g) in ind.genome.iter().enumerate() {
                let (lo, hi) = bounds[j];
                assert!(g >= lo && g <= hi, "Gene {j} = {g} out of [{lo}, {hi}]");
            }
        }
    }

    #[test]
    fn initial_fitness_is_neg_infinity() {
        let de = DifferentialEvolution::new(simple_bounds(3), 10, 0.8, 0.9, 42);
        for ind in &de.population {
            assert_eq!(ind.fitness, f64::NEG_INFINITY);
        }
    }

    #[test]
    fn best_starts_at_neg_infinity() {
        let de = DifferentialEvolution::new(simple_bounds(3), 10, 0.8, 0.9, 42);
        assert_eq!(de.best().fitness, f64::NEG_INFINITY);
    }

    // ---------------------------------------------------------------
    // Discrete gene rounding
    // ---------------------------------------------------------------

    #[test]
    fn discrete_genes_are_integers() {
        let bounds = vec![(0.0, 5.0), (-3.0, 3.0), (0.0, 4.0)];
        let discrete = vec![0, 2]; // genes 0 and 2 are discrete
        let de = DifferentialEvolution::with_discrete(bounds, 30, 0.8, 0.9, 42, discrete);

        for ind in &de.population {
            assert!(
                (ind.genome[0] - ind.genome[0].round()).abs() < 1e-10,
                "Discrete gene 0 = {} should be integer",
                ind.genome[0]
            );
            assert!(
                (ind.genome[2] - ind.genome[2].round()).abs() < 1e-10,
                "Discrete gene 2 = {} should be integer",
                ind.genome[2]
            );
        }
    }

    // ---------------------------------------------------------------
    // report_fitness updates best
    // ---------------------------------------------------------------

    #[test]
    fn report_fitness_updates_best() {
        let mut de = DifferentialEvolution::new(simple_bounds(2), 10, 0.8, 0.9, 42);
        de.report_fitness(3, 0.75);
        assert_eq!(de.best().fitness, 0.75);

        de.report_fitness(7, 0.90);
        assert_eq!(de.best().fitness, 0.90);

        // Lower fitness doesn't replace best
        de.report_fitness(1, 0.50);
        assert_eq!(de.best().fitness, 0.90);
    }

    // ---------------------------------------------------------------
    // generate_trials produces correct count
    // ---------------------------------------------------------------

    #[test]
    fn trials_count_equals_pop_size() {
        let mut de = DifferentialEvolution::new(simple_bounds(3), 15, 0.8, 0.9, 42);
        // Must evaluate initial pop first
        for i in 0..15 {
            de.report_fitness(i, 0.5);
        }
        let trials = de.generate_trials();
        assert_eq!(trials.len(), 15);
    }

    #[test]
    fn trials_within_bounds() {
        let bounds = vec![(-2.0, 3.0), (0.0, 10.0), (-1.0, 1.0)];
        let mut de = DifferentialEvolution::new(bounds.clone(), 20, 0.8, 0.9, 42);
        for i in 0..20 {
            de.report_fitness(i, 0.5);
        }

        let trials = de.generate_trials();
        for (idx, trial) in &trials {
            for (j, &g) in trial.iter().enumerate() {
                let (lo, hi) = bounds[j];
                assert!(
                    g >= lo && g <= hi,
                    "Trial for target {idx}, gene {j} = {g} out of [{lo}, {hi}]"
                );
            }
        }
    }

    // ---------------------------------------------------------------
    // Greedy selection: trial replaces parent if >=
    // ---------------------------------------------------------------

    #[test]
    fn greedy_selection_replaces_on_equal() {
        let mut de = DifferentialEvolution::new(simple_bounds(2), 10, 0.8, 0.9, 42);
        de.report_fitness(0, 0.5);

        let new_genome = vec![1.0, 2.0];
        de.report_trial_result(0, new_genome.clone(), 0.5); // equal fitness

        // Should replace (>= selection)
        assert_eq!(de.population[0].genome, new_genome);
    }

    #[test]
    fn greedy_selection_keeps_parent_if_worse() {
        let mut de = DifferentialEvolution::new(simple_bounds(2), 10, 0.8, 0.9, 42);
        de.report_fitness(0, 0.5);

        let old_genome = de.population[0].genome.clone();
        de.report_trial_result(0, vec![9.0, 9.0], 0.3); // worse

        assert_eq!(de.population[0].genome, old_genome);
        assert_eq!(de.population[0].fitness, 0.5);
    }

    #[test]
    fn skipped_trial_report_keeps_parent_unchanged() {
        let mut de = DifferentialEvolution::new(simple_bounds(2), 6, 0.8, 0.9, 42);
        for i in 0..6 {
            de.report_fitness(i, 0.4 + i as f64 * 0.01);
        }

        let before = de.population[0].clone();
        let _trials = de.generate_trials();

        assert_eq!(de.population[0].genome, before.genome);
        assert_eq!(de.population[0].fitness, before.fitness);
    }

    // ---------------------------------------------------------------
    // Convergence on a simple 1D function
    // ---------------------------------------------------------------

    #[test]
    fn converges_on_1d_quadratic() {
        // Maximize f(x) = -(x-3)^2 + 10.  Optimum at x=3, f=10.
        let bounds = vec![(0.0, 6.0)];
        let mut de = DifferentialEvolution::new(bounds, 10, 0.8, 0.9, 42);

        // Evaluate initial population
        for (i, genome) in de.pending_evaluations() {
            let x = genome[0];
            let fitness = -(x - 3.0).powi(2) + 10.0;
            de.report_fitness(i, fitness);
        }

        // Run 50 generations
        for _ in 0..50 {
            let trials = de.generate_trials();
            for (target, trial) in trials {
                let x = trial[0];
                let fitness = -(x - 3.0).powi(2) + 10.0;
                de.report_trial_result(target, trial, fitness);
            }
        }

        let best = de.best();
        assert!(
            (best.genome[0] - 3.0).abs() < 0.1,
            "Should converge near x=3, got x={:.4}",
            best.genome[0]
        );
        assert!(
            best.fitness > 9.9,
            "Should achieve fitness near 10, got {:.4}",
            best.fitness
        );
    }

    // ---------------------------------------------------------------
    // Determinism: same seed → same results
    // ---------------------------------------------------------------

    #[test]
    fn deterministic_with_same_seed() {
        let make_de = || {
            let mut de = DifferentialEvolution::new(simple_bounds(3), 10, 0.8, 0.9, 123);
            for i in 0..10 {
                de.report_fitness(i, i as f64 * 0.1);
            }
            de.generate_trials()
        };

        let trials1 = make_de();
        let trials2 = make_de();

        for ((i1, t1), (i2, t2)) in trials1.iter().zip(trials2.iter()) {
            assert_eq!(i1, i2);
            assert_eq!(t1, t2);
        }
    }

    // ---------------------------------------------------------------
    // seed_from_genome
    // ---------------------------------------------------------------

    #[test]
    fn seed_from_genome_places_seed_at_index_0() {
        let mut de = DifferentialEvolution::new(simple_bounds(3), 10, 0.8, 0.9, 42);
        let seed = vec![1.0, 2.0, 3.0];
        de.seed_from_genome(&seed, 0.1);

        assert_eq!(de.population[0].genome, seed);
    }

    #[test]
    fn seed_from_genome_resets_fitness() {
        let mut de = DifferentialEvolution::new(simple_bounds(3), 10, 0.8, 0.9, 42);
        de.report_fitness(0, 0.9);
        de.seed_from_genome(&vec![0.0; 3], 0.1);

        for ind in &de.population {
            assert_eq!(ind.fitness, f64::NEG_INFINITY);
        }
    }

    // ---------------------------------------------------------------
    // mean_fitness and fitness_std
    // ---------------------------------------------------------------

    #[test]
    fn mean_fitness_excludes_unevaluated() {
        let mut de = DifferentialEvolution::new(simple_bounds(2), 10, 0.8, 0.9, 42);
        de.report_fitness(0, 0.4);
        de.report_fitness(1, 0.6);
        // 8 others are NEG_INFINITY

        let mean = de.mean_fitness();
        assert!((mean - 0.5).abs() < 1e-10, "Mean should be 0.5, got {mean}");
    }

    #[test]
    fn fitness_std_zero_for_uniform_pop() {
        let mut de = DifferentialEvolution::new(simple_bounds(2), 5, 0.8, 0.9, 42);
        for i in 0..5 {
            de.report_fitness(i, 0.7);
        }
        assert!(
            de.fitness_std() < 1e-10,
            "Uniform fitness should have std=0"
        );
    }

    #[test]
    fn fitness_std_positive_for_varied_pop() {
        let mut de = DifferentialEvolution::new(simple_bounds(2), 4, 0.8, 0.9, 42);
        de.report_fitness(0, 0.2);
        de.report_fitness(1, 0.4);
        de.report_fitness(2, 0.6);
        de.report_fitness(3, 0.8);
        assert!(de.fitness_std() > 0.1);
    }

    // ---------------------------------------------------------------
    // Generation counter
    // ---------------------------------------------------------------

    #[test]
    fn generation_increments() {
        let mut de = DifferentialEvolution::new(simple_bounds(2), 10, 0.8, 0.9, 42);
        assert_eq!(de.generation(), 0);

        for i in 0..10 {
            de.report_fitness(i, 0.5);
        }
        let _ = de.generate_trials();
        assert_eq!(de.generation(), 1);

        let _ = de.generate_trials();
        assert_eq!(de.generation(), 2);
    }

    // ---------------------------------------------------------------
    // pending_evaluations
    // ---------------------------------------------------------------

    #[test]
    fn pending_evaluations_initially_all() {
        let de = DifferentialEvolution::new(simple_bounds(2), 10, 0.8, 0.9, 42);
        assert_eq!(de.pending_evaluations().len(), 10);
    }

    #[test]
    fn pending_evaluations_shrinks_after_report() {
        let mut de = DifferentialEvolution::new(simple_bounds(2), 10, 0.8, 0.9, 42);
        de.report_fitness(0, 0.5);
        de.report_fitness(1, 0.5);
        assert_eq!(de.pending_evaluations().len(), 8);
    }
}
